version: "3.1"

services:
  oracledb:
    build:
      context: oracledb
    ports:
      - "1521:1521"
      - "5500:5500"
    volumes:
      - "oradata:/opt/oracle/oradata"

  myapp:
    image: myapp:latest
    command: -Soracle
    ports:
      - "8080:8080"

  prometheus:
    build:
      context: prometheus
    ports:
      - "9090:9090"
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--storage.tsdb.path=/prometheus"
    volumes:
      - "prometheus:/prometheus"

volumes:
  oradata:
  prometheus: